name: Go Build
on:
- push
- pull_request

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - env:
          CGO_ENABLED: "0"
        run: go build -o powermeter_exporter
