name: Go Build
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        go: [ '1.20', '1.21', '1.22' ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - env:
          CGO_ENABLED: "0"
        run: go build -o powermeter_exporter
