name: Go Build
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go: [ '1.17', '1.18', '1.19' ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - env:
          CGO_ENABLED: "0"
        run: go build -o powermeter_exporter
